[package]
name = "zed-42header"
version = "0.1.1"
edition = "2021"
authors = ["gade-oli <gade-oli@student.42madrid.com>"]
description = "42 School file header"
license = "MIT"
repository = "https://github.com/fkyros/zed-42header"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
zed_extension_api = "0.7.0"

[workspace]
members = [".", "server"]
default-members = ["."]
