id = "42header"
name = "42 Header"
version = "0.1.0"
schema_version = 1
authors = ["gade-oli <gade-oli@student.42madrid.com>"]
description = "Community-driven port of the 42 School file header for Zed Editor"
repository = "https://github.com/fkyros/zed-42header"

[language_servers.header42-lsp]
name = "42 Header Language Server"
languages = [
    "Assembly",
    "Bash",
    "C",
    "C++",
    "CSS",
    "Fortran",
    "Go",
    "HTML",
    "Java",
    "JavaScript",
    "Kotlin",
    "LaTeX",
    "Lua",
    "Makefile",
    "OCaml",
    "PHP",
    "Python",
    "Rust",
    "SCSS",
    "Shell Script",
    "TSX",
    "TypeScript",
    "Vimscript",
    "XML"
]
